[우선순위 큐] 9월 19일
Altu-Bitu/Altu-Bitu-min pull request #3
Opened 2021-09-19 06:52 UTC by mingulmangul

9월 14일 - 우선순위 큐
과제 제출합니다.

2021-09-19 07:47 UTC, bsa0322 requested changes
p1. 너무 잘 풀어주셨어요!! 주석 설명도 완전 꼼꼼해서 보기 좋았습니다! 탑 문제만 수정 후 저 다시 리뷰어로 호출해주세요! 수고하셨습니다~!

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/11286.cpp
> +};
👍👍👍

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +                    cout << 0 << '\n';
p3. bool 자료형을 출력하면 어떻게 되는지 보시겠어요? 이 코드 한 줄로 줄일 수 있을 것 같아요!

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +                    s[x] = true;
p3. p3. s[x]의 상태는 딱 두 가지고, 둘은 서로 반대니까 이 부분 코드도 한 줄로 줄일 수 있을 것 같아요!

더불어 지금도 너무 잘 풀어주셨는데, 비트의 연산의 성질을 활용한 비트마스킹이라는 알고리즘이 있어요! 이 문제의 풀이로 활용되니 한 번 공부해보셔도 좋을 것 같아요! 쉽지는 않은 알고리즘이라 그냥 진짜 추천만 드립니다!

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +        }
p3. 아래에서 입력이 이루어지니, 마지막에 검사해서 1을 넣어주거나 아님 other_mileage.top()을 넣어주는 거로 하면 코드를 줄이고, 반복문의 사용도 줄일 수 있을 것 같아요!

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +        }
p3. 수업시간에 배운 응용문제를 잘 활용해서 풀어주셨어요! 👍 

추가로 코멘트를 남기자면, 이 문제는 우선순위 큐 사용 없이도 풀이가 가능해요

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +    }
p2. 함수화 해봐도 좋을 것 같아요

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/2493.cpp
> +*/
p1. 우선순위 큐를 활용해서 너무 잘 풀어주셨는데, 사실 이 문제는 우선순위 큐의 특징인 우선순위가 필요 없는 문제에요! 탑은 그 자리에 고정되어 있고, 본인 기준 가장 왼쪽에 있고 높은 탑이 수신탑이므로, 어차피 pop()연산이 계속 이루어지죠. 어떤 자료구조를 활용해 볼 수 있을까요? 수정해서 다시 커밋해주세요!

2021-09-19 07:47 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +}
오오 이렇게 함수화 하는 건 생각 못해봤는데, 아주 잘 해주셨어요! 👍

2021-09-20 02:20 UTC, mingulmangul commented
피드백 감사합니다!! 수정한 코드 리뷰 부탁드려요🥰

2021-09-20 03:07 UTC, bsa0322 reviewed
p3. 좋아요! 2493 문제는 우선순위의 사용이 없으니 더 맞는 자료구조는 stack 이라는 걸 잘 찾아주셨어요! 코드가 더 깔끔해질 수 있을 것 같아 가독성코멘트만 추가했어요. 수정해서 머지해주셔도 괜찮고 지금 머지해주셔도 괜찮아요! 수고하셨습니다~!

2021-09-20 03:07 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +                cout << s[x] << '\n';
👍👍👍

2021-09-20 03:07 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +    cout << calcNumOfSubject(my_mileage, m);
👍👍👍

2021-09-20 03:07 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/2493.cpp
> +    stack<pair<int, int>> towers; // 왼쪽에 있는 탑들을 저장
좋아요! 이 문제는 stack 만으로 풀 수 있죠.

2021-09-20 03:07 UTC, bsa0322 commented on 9월 14일 - 우선순위 큐/2493.cpp
> +        }
p3. 조금 더 코멘트를 드리면, 이 코드 리팩토링해서 더 깔끔하게 작성할 수 있을 것 같아요. 우선 지금 반복이 되어야 할 부분은 40-44줄밖에 없죠! 그러면 겉에 큰 while문이 꼭 필요할까요? 
그리고 towers.push(tower)도 중복되고 있어요. 
또한 47번째 줄의 조건문은 애초에 수신탑이 있는지 검사한 후 이루어지면 효과가 없어요. 탑의 높이가 같다면 수신탑이 될 수 없으니까요. 따라서 어디에 합칠 수 있을까요?

2021-09-20 03:08 UTC, bsa0322 approved these changes

2021-09-23 11:33 UTC, merged